language: node_js
node_js:
  - "4.4.2"
before_script:
  - npm install -g grunt-cli
before_install:
  - npm install -g npm
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick
  - sudo apt-get install graphicsmagick
